var stateData = {
	usa: {
		name: 'No class selected',
		abbr: 'N/A',
		capitol: 'N/A',
		pop: 'N/A',
		statehood: 'N/A',
		mammal: 'N/A',
		bird: 'N/A',
		tree: 'N/A',
		flower: 'N/A',
		nickname: 'N/A'
	},
	al: {
		name: 'Dark Knight',
		abbr: 'Warrior',
		capitol: 'Explorer -> Swordsman -> Spearman -> Berserker -> Dark Knight',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Very good mobbing, lots of hp due to hyperbody.',
		bird: 'Strength, STR',
		tree: 'Lots of Final Damage so your range is inflated.',
		flower: 'Dark Sphere, Beholder Impact',
		nickname: 'Physical'
	},
	ak: {
		name: 'Hero',
		abbr: 'Warrior',
		capitol: 'Explorer -> Swordsman -> Fighter -> Crusader -> Hero ',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Very good bosser',
		bird: 'Strength, STR',
		tree: 'Bad mobbing due to short reach',
		flower: 'Sword of Burning Soul, World Reaver',
		nickname: 'Physical'
	},
	az: {
		name: 'Paladin',
		abbr: 'Warrior',
		capitol: 'Explorer -> Swordsman -> Page -> White Knight -> Paladin',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Semi-good mobber, very flashy skills',
		bird: 'Strength, STR',
		tree: 'Bad mobbing due to short reach, slow skills',
		flower: 'Holy Unity, Blessed Hammer',
		nickname: 'Physical'
	},
	ar: {
		name: 'Night Lord',
		abbr: 'Thief',
		capitol: 'Explorer -> Thief -> Assassin -> Hermit -> Night Lord',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Very good mobbing due to showdown, good mobility with haste',
		bird: 'Luck, LCK',
		tree: 'Squishy, dies easily',
		flower: 'Spread Throw, Throwing Star',
		nickname: 'Physical'
	},
	ca: {
		name: 'Shadower',
		abbr: 'Thief',
		capitol: 'Explorer -> Thief -> Bandit -> Chief Bandit -> Shadower',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Slow training, flashy skills',
		bird: 'Luck, LCK',
		tree: 'Low damage',
		flower: 'Shadow Assault, Eviscerate',
		nickname: 'Physical'
	},
	co: {
		name: 'Dual Blade',
		abbr: 'Thief',
		capitol: 'Dual Blade -> Rogue -> Blade Recruit -> Blade Acolyte -> Blade Specialist -> Blade Lord -> Blade Master',
		pop: 'Rogue thieves who have strayed from their original path, following Lady Syl instead of Dark Lord',
		statehood: 'Kerning City',
		mammal: 'Flashy Skills, fast leveling',
		bird: 'Luck, LCK',
		tree: 'N/A',
		flower: 'Blade Storm, Karmic Fury',
		nickname: 'Physical'
	},
	ct: {
		name: 'Ice Lightning Mage',
		abbr: 'Wizard',
		capitol: 'Explorer -> Magician -> Ice Lightning Wizard -> Ice Lightning Mage -> Ice Lightning Arch-Mage',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Big mobbing skills fifth job',
		bird: 'Intelligence, INT',
		tree: 'N/A',
		flower: 'Ice Age, Bolt Barrage',
		nickname: 'Magical'
	},
	de: {
		name: 'Fire Poison Mage',
		abbr: 'Wizard',
		capitol: 'Explorer -> Magician -> Fire Poison Wizard -> Fire Poison Mage -> Fire Poison Arch-Mage',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Big mobbing skills fifth job',
		bird: 'Intelligence, INT',
		tree: 'N/A',
		flower: 'DOT Punisher, Venom Spore',
		nickname: 'Magical'
	},
	fl: {
		name: 'Bishop',
		abbr: 'Wizard',
		capitol: 'Explorer -> Magician -> Cleric -> Priest -> Bishop',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'HOLY SYMBOL',
		bird: 'Intelligence, INT',
		tree: 'N/A',
		flower: 'Benediction, Angel of Libra',
		nickname: 'Magical'
	},
	ga: {
		name: 'MarksMan',
		abbr: 'Bowman',
		capitol: 'Explorer -> Archer -> Crossbowman -> Sniper -> Marksman ',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Good single target dps',
		bird: 'Dexterity, DEX',
		tree: 'N/A',
		flower: 'True Sniping, Split Arrow',
		nickname: 'Physical'
	},
	hi: {
		name: 'Corsair',
		abbr: 'Pirate',
		capitol: 'Explorer -> Pirate -> Gunslinger -> Outlaw -> Corsair',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Summon class',
		bird: 'Dexterity, DEX',
		tree: 'N/A',
		flower: 'Bullet Party, Deadeye',
		nickname: 'Physical'
	},
	id: {
		name: 'Buccaneer',
		abbr: 'Pirate',
		capitol: 'Explorer -> Pirate -> Brawler -> Marauder -> Buccaneer',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Strong skills, flashy.',
		bird: 'Strenth, STR',
		tree: 'N/A',
		flower: 'Transform, Serpent Screw',
		nickname: 'Physical'
	},
	il: {
		name: 'Mercedes',
		abbr: 'Dual Bowguns',
		capitol: 'Mercedes',
		pop: 'Queen of elves from Elluel',
		statehood: 'Elluel',
		mammal: 'Combo-skills, flashy',
		bird: 'Dexterity, DEX',
		tree: 'N/A',
		flower: 'Spirit of Elluel, Sylvidia',
		nickname: 'Physical'
	},
	il: {
		name: 'Mercedes (HEROES)',
		abbr: 'Dual Bowguns',
		capitol: 'Mercedes',
		pop: 'Queen of elves from Elluel',
		statehood: 'Elluel',
		mammal: 'Combo-skills, flashy',
		bird: 'Dexterity, DEX',
		tree: 'N/A',
		flower: 'Spirit of Elluel, Sylvidia',
		nickname: 'Physical'
	},
	'in': {
		name: 'Luminous (HEROES)',
		abbr: 'Magician',
		capitol: 'Luminous',
		pop: 'A burdened mage that has half of the black mages power within him',
		statehood: 'Ellinia',
		mammal: 'N/A',
		bird: 'Intelligence, INT',
		tree: 'N/A',
		flower: 'Gate of Light, Punishing Resonator',
		nickname: 'Magical'
	},
	ia: {
		name: 'Shade/Eunwol (Forgotten Hero)',
		abbr: 'Pirate',
		capitol: 'Shade',
		pop: 'The forgotten sixth hero of the MapleWorld, chose to give up his existence to save his friends and the world',
		statehood: 'Fox Village',
		mammal: 'N/A',
		bird: 'Strength, STR',
		tree: 'N/A',
		flower: 'Spirit Flow, Ghost Disposition',
		nickname: 'Physical'
	},
	ks: {
		name: 'Aran (HEROES)',
		abbr: 'Warrior',
		capitol: 'Aran',
		pop: 'A strong warrior who was encased in ice and ended up in the snowy town of Rien, with the help of a spirit named Maha',
		statehood: 'Rien',
		mammal: 'N/A',
		bird: 'Stength, STR',
		tree: 'N/A',
		flower: 'Mahas Fury, Mahas Carnage',
		nickname: 'Physical'
	},
	ky: {
		name: 'Phantom (HEROES)',
		abbr: 'Thief',
		capitol: 'Phantom',
		pop: 'A mysterious Phantom who is known across the Maple World, very elusive. Uses a cane and cards as his weapon of choice.',
		statehood: 'Lumiere',
		mammal: 'N/A',
		bird: 'Luck, LUK',
		tree: 'N/A',
		flower: 'Joker, BlackJack',
		nickname: 'Physical'
	},
	la: {
		name: 'Evan (HEROES)',
		abbr: 'Magician',
		capitol: 'Evan',
		pop: 'Succeeding the legendary hero Freud, Evan was just a farm boy who stumbled upon the egg of an anicent dragon. Uses wands/staffs alongside the power of the dragon Mir.',
		statehood: 'Utahs Farm',
		mammal: 'N/A',
		bird: 'Intelligence, INT',
		tree: 'N/A',
		flower: 'Elemental Barrage, Dragon Break',
		nickname: 'Magical'
	},
	me: {
		name: 'Kaiser',
		abbr: 'Warrior',
		capitol: 'Kaiser',
		pop: 'Taking ahold the ancient armor of the previous Kaiser, the boy is the next in line to the name. Uses a two handed blade.',
		statehood: 'Grandis',
		mammal: 'N/A',
		bird: 'Strength, STR',
		tree: 'N/A',
		flower: 'Guardian of Nova, Will of Sword: Strike',
		nickname: 'Physical'
	},
	md: {
		name: 'Angelic Buster',
		abbr: 'Pirate',
		capitol: 'Angelic Buster',
		pop: 'Childhood friends with the boy who became the next Kaiser, Tear stumbled upon an ancient dragon shooter and became Angelic Buster',
		statehood: 'Grandis',
		mammal: 'N/A',
		bird: 'Dexterity, DEX',
		tree: 'N/A',
		flower: 'Sparkle Burst, Spotlight',
		nickname: 'Physical'
	},
	ma: {
		name: 'Massachusetts',
		abbr: 'MA',
		capitol: 'Boston',
		pop: '6,692,824',
		statehood: '1788',
		mammal: 'Right Whale',
		bird: 'Black-Capped Chickadee',
		tree: 'American Elm',
		flower: 'Mayflower',
		nickname: 'Bay State'
	},
	mi: {
		name: 'Michigan',
		abbr: 'MI',
		capitol: 'Lansing',
		pop: '9,895,622',
		statehood: '1837',
		mammal: 'White-Tailed Deer',
		bird: 'Robin',
		tree: 'White Pine',
		flower: 'Apple Blossom',
		nickname: 'Wolverine State/Great Lake State'
	},
	mn: {
		name: 'Minnesota',
		abbr: 'MN',
		capitol: 'Saint Paul',
		pop: '5,420,380',
		statehood: '1858',
		mammal: 'N/A',
		bird: 'Loon',
		tree: 'Norway Pine',
		flower: 'Lady Slipper',
		nickname: 'North Star State/Land of 10,000 Lakes'
	},
	ms: {
		name: 'Mississippi',
		abbr: 'MS',
		capitol: 'Jackson',
		pop: '2,991,207',
		statehood: '1817',
		mammal: 'Bottlenosed Dolphin',
		bird: 'Mockingbird',
		tree: 'Magnolia',
		flower: 'Magnolia',
		nickname: 'Magnolia State'
	},
	mo: {
		name: 'Missouri',
		abbr: 'MO',
		capitol: 'Jefferson City',
		pop: '6,044,171',
		statehood: '1821',
		mammal: 'Missouri Mule',
		bird: 'Bluebird',
		tree: 'Flowering Dogwood',
		flower: 'White Hawthorn Blossom',
		nickname: 'Show Me State'
	},
	mt: {
		name: 'Montana',
		abbr: 'MT',
		capitol: 'Helena',
		pop: '1,015,165',
		statehood: '1889',
		mammal: 'Grizzly Bear',
		bird: 'Western Meadowlark',
		tree: 'Ponderosa Pine',
		flower: 'Bitterroot',
		nickname: 'Treasure State'
	},
	ne: {
		name: 'Nebraska',
		abbr: 'NE',
		capitol: 'Lincoln',
		pop: '1,868,516',
		statehood: '1867',
		mammal: 'White-Tailed Deer',
		bird: 'Western Meadowlark',
		tree: 'Cottonwood',
		flower: 'Goldenrod',
		nickname: 'Cornhusker State'
	},
	nv: {
		name: 'Nevada',
		abbr: 'NV',
		capitol: 'Carson City',
		pop: '2,790,136',
		statehood: '1864',
		mammal: 'Desert Bighorn Sheep',
		bird: 'Mountain Bluebird',
		tree: 'Single-Leaf Piñon',
		flower: 'Sagebrush',
		nickname: 'The Silver State'
	},
	nh: {
		name: 'New Hampshire',
		abbr: 'NH',
		capitol: 'Concord',
		pop: '1,323,459',
		statehood: '1788',
		mammal: 'White-Tailed Deer',
		bird: 'Purple Finch',
		tree: 'White Birch',
		flower: 'Purple Lilac',
		nickname: 'Granite State'
	},
	nj: {
		name: 'New Jersey',
		abbr: 'NJ',
		capitol: 'Trenton',
		pop: '1,323,459',
		statehood: '1787',
		mammal: 'Horse',
		bird: 'Eastern Goldfinch',
		tree: 'Red Oak',
		flower: 'Common Violet',
		nickname: 'Garden State'
	},
	nm: {
		name: 'New Mexico',
		abbr: 'NM',
		capitol: 'Santa Fe',
		pop: '1,323,459',
		statehood: '1912',
		mammal: 'American Black Bear',
		bird: 'Greater Roadrunner',
		tree: 'Piñon Pine',
		flower: 'Soaptree Yucca',
		nickname: 'Land of Enchantment'
	},
	ny: {
		name: 'New York',
		abbr: 'NY',
		capitol: 'Albany',
		pop: '19,651,127',
		statehood: '1788',
		mammal: 'Beaver',
		bird: 'Bluebird',
		tree: 'Sugar Maple',
		flower: 'Rose',
		nickname: 'Empire State'
	},
	nc: {
		name: 'North Carolina',
		abbr: 'NC',
		capitol: 'Raleigh',
		pop: '9,848,060',
		statehood: '1789',
		mammal: 'Gray Squirrel',
		bird: 'Cardinal',
		tree: 'Pine',
		flower: 'Dogwood',
		nickname: 'Old North State/Tar Heel State'
	},
	nd: {
		name: 'North Dakota',
		abbr: 'ND',
		capitol: 'Bismarck',
		pop: '723,393',
		statehood: '1889',
		mammal: 'Nokota Horse',
		bird: 'Western Meadowlark',
		tree: 'American Elm',
		flower: 'Wild Prairie Rose',
		nickname: 'Peace Garden State/Flickertail State/Roughrider State'
	},
	oh: {
		name: 'Ohio',
		abbr: 'OH',
		capitol: 'Columbus',
		pop: '11,570,808',
		statehood: '1803',
		mammal: 'White-Tailed Deer',
		bird: 'Cardinal',
		tree: 'Ohio Buckeye',
		flower: 'Red Carnation',
		nickname: 'Buckeye State'
	},
	ok: {
		name: 'Oklahoma',
		abbr: 'OK',
		capitol: 'Oklahoma City',
		pop: '3,850,568',
		statehood: '1907',
		mammal: 'Raccoon',
		bird: 'Scissor-Tailed Flycatcher',
		tree: 'Redbud',
		flower: 'Red Carnation',
		nickname: 'Sooner State'
	},
	or: {
		name: 'Oregon',
		abbr: 'OR',
		capitol: 'Salem',
		pop: '3,930,065',
		statehood: '1859',
		mammal: 'American Beaver',
		bird: 'Western Meadowlark',
		tree: 'Douglas-Fir',
		flower: 'Oregon Grape',
		nickname: 'Beaver State'
	},
	pa: {
		name: 'Pennsylvania',
		abbr: 'PA',
		capitol: 'Harrisburg',
		pop: '12,773,801',
		statehood: '1787',
		mammal: 'White-Tailed Deer',
		bird: 'Ruffed Grouse',
		tree: 'Hemlock',
		flower: 'Mountain Laurel',
		nickname: 'Keystone State'
	},
	ri: {
		name: 'Rhode Island',
		abbr: 'RI',
		capitol: 'Providence',
		pop: '1,051,511',
		statehood: '1790',
		mammal: 'N/A',
		bird: 'Rhode Island Hen',
		tree: 'Red Maple',
		flower: 'Violet',
		nickname: 'The Ocean State'
	},
	sc: {
		name: 'South Carolina',
		abbr: 'SC',
		capitol: 'Columbia',
		pop: '4,774,839',
		statehood: '1788',
		mammal: 'White-Tailed Deer',
		bird: 'Carolina Wren',
		tree: 'Sabal Palmetto',
		flower: 'Yellow Jessamine',
		nickname: 'Palmetto State'
	},
	sd: {
		name: 'South Dakota',
		abbr: 'SD',
		capitol: 'Pierre',
		pop: '844,877',
		statehood: '1889',
		mammal: 'Coyote',
		bird: 'Chinese Ring-Necked Pheasant',
		tree: 'Black Hills Spruce',
		flower: 'Pasque',
		nickname: 'Mount Rushmore State'
	},
	tn: {
		name: 'Tennessee',
		abbr: 'TN',
		capitol: 'Nashville',
		pop: '6,495,978',
		statehood: '1796',
		mammal: 'Raccoon',
		bird: 'Mockingbird',
		tree: 'Tulip Poplar',
		flower: 'Iris',
		nickname: 'Volunteer State'
	},
	tx: {
		name: 'Texas',
		abbr: 'TX',
		capitol: 'Austin',
		pop: '26,448,193',
		statehood: '1845',
		mammal: 'Longhorn',
		bird: 'Mockingbird',
		tree: 'Pecan',
		flower: 'Bluebonnet',
		nickname: 'Lone Star State'
	},
	ut: {
		name: 'Utah',
		abbr: 'UT',
		capitol: 'Salt Lake City',
		pop: '2,900,872',
		statehood: '1896',
		mammal: 'Rock-Mountain Elk',
		bird: 'California Gull',
		tree: 'Blue Spruce',
		flower: 'Sego Lily',
		nickname: 'The Beehive State'
	},
	vt: {
		name: 'Vermont',
		abbr: 'VT',
		capitol: 'Montpelier',
		pop: '626,630',
		statehood: '1791',
		mammal: 'Morgan Horse',
		bird: 'Hermit Thrush',
		tree: 'Sugar Maple',
		flower: 'Red Clover',
		nickname: 'Green Mountain State'
	},
	va: {
		name: 'Virginia',
		abbr: 'VA',
		capitol: 'Richmond',
		pop: '8,260,405',
		statehood: '1788',
		mammal: 'Virginia Big-Eared Bat',
		bird: 'Cardinal',
		tree: 'Flowering Dogwood',
		flower: 'Flowering Dogwood',
		nickname: 'Old Dominion State'
	},
	wa: {
		name: 'Washington',
		abbr: 'WA',
		capitol: 'Olympia',
		pop: '6,971,406',
		statehood: '1889',
		mammal: 'Olympic Marmot',
		bird: 'Willow Goldfinch',
		tree: 'Western Hemlock',
		flower: 'Rhododendron',
		nickname: 'The Evergreen State'
	},
	dc: {
		name: 'Bow Master',
		abbr: 'Bowman',
		capitol: 'Explorer -> Archer -> Hunter -> Ranger -> BowMaster ',
		pop: 'An amnesiac adventurer starting their Maple world journey from Maple Island to Lith Harbor of Victoria Island',
		statehood: 'Maple Island',
		mammal: 'Sharp Eyes is very good, good mobbing',
		bird: 'Dexterity, DEX',
		tree: 'N/A',
		flower: 'Arrow Rain, After image shot',
		nickname: 'Physical'
	},
	wv: {
		name: 'West Virginia',
		abbr: 'WV',
		capitol: 'Charleston',
		pop: '1,854,304',
		statehood: '1863',
		mammal: 'Black Bear',
		bird: 'Cardinal',
		tree: 'Sugar Maple',
		flower: 'Rhododendron',
		nickname: 'Mountain State'
	},
	wi: {
		name: 'Wisconsin',
		abbr: 'WI',
		capitol: 'Madison',
		pop: '5,742,713',
		statehood: '1848',
		mammal: 'Badger',
		bird: 'Robin',
		tree: 'Sugar Maple',
		flower: 'Wood Violet',
		nickname: 'Badger State'
	},
	wy: {
		name: 'Wyoming',
		abbr: 'WY',
		capitol: 'Cheyenne',
		pop: '582,658',
		statehood: '1890',
		mammal: 'American Buffalo',
		bird: 'Western Meadlowlark',
		tree: 'Plains Cottonwood',
		flower: 'Indian Paintbrush',
		nickname: 'Equality State'
	}
};
